### ISSUE TITLE
Can't connect using $dbh

### ISSUE THREAD

**Issue by davehodg** [akiym/TheSchwartz#10]
I'm probably missing something here. At the end of the man page, it tells me how to connect with a database handle.

In my case I have:

```
my $Dbh = Dbh();
my $client = TheSchwartz->new(databases => [{ driver => $Dbh }]);
```

$Dbh is `$VAR1 = bless( {}, 'DBI::db' );`.

TheSchwartz throws:

```
Can't locate object method "get_dbh" via package "DBI::db" at /usr/local/share/perl5/TheSchwartz.pm line 78.
 at /usr/local/share/perl5/TheSchwartz.pm line 78.
	TheSchwartz::hash_databases('TheSchwartz=HASH(0x6980030)', 'ARRAY(0x69601c0)') called at /usr/local/share/perl5/TheSchwartz.pm line 55
	TheSchwartz::new('TheSchwartz', 'databases', 'ARRAY(0x69601c0)') called at scripts/trigger-helper line 79
```

What am I missing?

**Comment by akiym** [comment]
You have to pass `Data::ObjectDriver::Driver::DBI` object. Please see this section: https://metacpan.org/pod/TheSchwartz#PASSING-IN-AN-EXISTING-DRIVER

**Comment by davehodg** [comment]
That comment is a regurgitation of the manual, which obviously didn't work for me. ->new([ $dbh ]) like the man page was a non-starter for me. Using the database credentials worked much better.
