### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by kalydrae** [akiym/TheSchwartz#2]
Hi there, i'm getting multiple errors trying to install TheSchwartz 1.14
I'm running from cmd with elevated privileges.

> No such signal: SIGUSR1 at t/client-time-unsync.t line 28.

> Can't teardown ts1: Permission denied at ./t/lib/db-common.pl line 230.

[build.log](https://github.com/akiym/TheSchwartz/files/3759275/build.log)

**Comment by akiym** [comment]
Not supported on Windows...

**Comment by akiym** [comment]
Tests has been broken for a long time on Windows, so I was confused about supporting on Windows. 
http://matrix.cpantesters.org/?dist=TheSchwartz+1.12

The problem on this issue was fixed and I released v1.15. Thank you for your report!
