### ISSUE TITLE
What is the point of sorting jobs by priority if they are going to be shuffled?

### ISSUE THREAD

**Issue by robrwo** [akiym/TheSchwartz#7]
The `find_job_for_workers` method will request jobs in order of priority and job id (or just jobid).

But then ` _grab_a_job` shuffles the jobs.  So unless one has more than 50 (batch-size) jobs in the queue, this ordering doesn't matter. The jobs will be shuffled.

The only workaround this is to set the batch size to 1.

This seems confusing and counter-intuitive.

**Comment by akiym** [comment]
Going back history, this was added by https://github.com/akiym/TheSchwartz/commit/bcd19e3bc9b5bb19db4e3e14533bd74ebb213aed and details can be found here: https://rt.cpan.org/Public/Bug/Display.html?id=99075
> We had an issue at $dayjob where the job queue was not processing the queue in roughly the order they were created causing issues when a large number of jobs (>30,000) were queued. This patch changes the sort order when prioritze is set to "priority DESC, jobid ASC"

> NOTE: the order for prioritize is not gauranteed unless FIND_JOB_BATCH_SIZE is set to 1. This is due to _grab_a_job running shuffle. See RT #72815

**Comment by robrwo** [comment]
Ok, this doesn't seem well documented.

**Comment by robrwo** [comment]
I would suggest adding an option to control job shuffling. It would be enabled by default, for backwards compatibility.

**Comment by akiym** [comment]
Released [TheSchwartz 1.16](https://metacpan.org/release/AKIYM/TheSchwartz-1.16) with patches #9 applied.
